# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # On DELL XPS13, this is necessary to have backlight controls working. See:
  # https://wiki.archlinux.org/index.php/Dell_XPS_13_(7390)
  # https://unix.stackexchange.com/a/483538/45689
  # https://gist.github.com/domenkozar/b3c945035af53fa816e0ac460f1df853#backlight-intel-works-out-of-the-box
  # boot.kernelParams = [ "acpi_backlight=intel" ];
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/78fc3f7f-8893-498a-8e2a-7a28f2695df1";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7D02-F589";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/d3dd093f-cf90-4f0b-b91d-4573fd983db8"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
