# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # On DELL XPS13, this is necessary to have backlight controls working. See:
  # https://wiki.archlinux.org/index.php/Dell_XPS_13_(7390)
  # https://unix.stackexchange.com/a/483538/45689
  # https://gist.github.com/domenkozar/b3c945035af53fa816e0ac460f1df853#backlight-intel-works-out-of-the-box
  # boot.kernelParams = [ "acpi_backlight=intel" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/dca8c5f6-e023-43f1-87f2-12917c6b653d";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0065-57C5";
    fsType = "vfat";
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # High-DPI console
  console.font =
    lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
